version: '3.3'
services:
  tensorflow:
    build:
      context: ./docker
    restart: always
    container_name: tensorflow
    environment:
     - PASSWORD=1q2w3e
    volumes:
      - ./notebooks:/notebooks
    restart: always
    ports:
        - "8888:8888"
        - "6006:6006"
